language: node_js
node_js:
- '4.2'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_install:
- npm install -g grunt-cli
notifications:
  email: false
env:
  global:
  - secure: yjS+W13v9LJ0quczTfNZyGgsdFoV5dITmMkCd6Y8h9bIvETQt+IEur/ak7nQrixDxNyvi0YyNarHE9wJLEP0hRsdEPiRIbLNkugpaaGUPB9Pb9DWu0zdWQPrI2+QHY3Q+lb8N/40I6F34WUS6xHFkdT5RJOYYpE67X221EBJUrvVg5jod9ENlT/7BSX21K0UpJgZSL33CmEIyXri7kTIumjxo9hte+HtLYZ8fXUPCcWpvtLtKAdwOrME0Y6IjlIIsZ6dVioRzegMTR0He2z9DHr1beUkgOGW+FvPb46dt6CLJOf0UR77QR674A5WmcvgfsZicXUiBW/X9ImxBvKR2AKr1x1SbozKbEao8Q1ZHCMoN19RuqjkvlK65HWHw4u67c5XWeQuEJRaWRuz8clhhmFlwzFQLJqYZe7O3bD9ogiBx+zqZJarKDgsPIymSEr5LBfP+RLBd1+CGNKF+7lpEfQnbs7jPOAIvgxQoPOcXK8zAGuMBZHg8J5rAc+3Io84m1bjrXkPuB07rQ5G9ITbN+GRO0Gp+kx44z7m+g6ZnjP73SumfEAZgyWmKmPtCdafXER25ZXc7hQ2mztEdCqRpNmGBSf+FupJttuvPg97qUmyQhGcd/j8pz+qHtAZiRMnKTb6sV9mvztnXgG4b8HPbKh0Hnd+oHUNkDxeMoenNAI=
  - secure: SaODbnFqO9ONvj6uU/fZHs0unXJ40NbQBGOaJX0N4zKE1p7GoJNeR47xiAlIb5EABs1QerQNaLE3gUkcWtFFK6a95tRVxGUJ6MUeg2kzXl5CRvKxe78MUqdvGyBHfHiH1hAnD0OKSPuMV64nGFB1rs3m/toNOL6GWknv+io6qlJwMJ3tEjmO9NacYoffpAc1BStKQSAVUu+E3T2zWb0ZtGptOIx0+cx7bfHI15YGkDr9dJcNOHhZMZqIBg1xEmDXUaUphaDDjlRnNtnEKEsZ/5glJ+exQooXlm5m5pWJ3ueVEBC56onJMzlATAnobnyRKhcoGOQmYTZoHhapchmpWSLl7+enB3VWKcfL8VKIoh/IP8DOsP4tsZOMJRhRat9DGqZDjugLANk1LUKMYI/p5MiTWTw0UvVtZ6DorV5Mn4Ot2ot5Z/D4QpHZOUNRF3vijkyWAeRuFGMA2YiheoiKAKbgHbZecbm1K6gb4+AIBnt6Jpt/8iHcYXgktG6H82olAtXBD7nLtpv/Als5l23zn3nIGHmw/IqcKAwU7xHYrBR4qWWiog1I7HFDMUGNFc/9DnOhrtNk7uLO1yidyLK6Rq491FbQsXmopMApnaWYGyUnLlwguIVpn5YzdBV9gNe7Do1n7AM6ZNImXpKADV/Q8UczSVjg/kFEIFj06AInNQA=
